### ISSUE TITLE
[Bug][Android] Language is not switched in preview when the implementation of StringsBindings is used

### ISSUE THREAD

**Issue by tkhs0604** [DroidKaigi/conference-app-2023#509] opened 2023-08-15 01:07 UTC
**Describe the bug**
As the subject says, language is not switched in preview when the implementation of StringsBindings is used.
Found it from: https://github.com/DroidKaigi/conference-app-2023/pull/481#issuecomment-1677666124

**To Reproduce**
1. Implement StringsBindings
2. Use the above implementation in your composable
3. Create previews for the composable
4. Add locale settings to the `@Preview` parameter

**Expected behavior**
Japanese and English can be switched properly in preview

**Screenshots**
N/A

**Comment by Corvus400** [comment] 2023-08-15 01:17
It looks difficult, but I would like to try it.🙋

**Comment by tkhs0604** [comment] 2023-08-15 01:32
@Corvus400 
Thank you for challenging it! Assigned 💪

**Comment by Corvus400** [comment] 2023-08-15 18:03
No solution has been found yet. 😔
All I know from observing the code now is that Android Studio Preview depends on the current language settings of macOS.
Perhaps macOS language settings are used [in this section](https://github.com/DroidKaigi/conference-app-2023/blob/main/core/designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2023/designsystem/strings/Lang.kt#L6) in Preview.
If I change the language setting of macOS to English, the Preview will be in English.
This is fine when built into the Android JVM environment, but in the Android Studio JVM environment, the code needs to be rewritten to depend on the externally given value (the Locale value in Preview).
The problem is that how this can be accomplished still needs to be investigated. 😕

**Comment by tkhs0604** [comment] 2023-08-16 00:42
@Corvus400 
Thank you so much for your investigation 🙇‍♂️

> All I know from observing the code now is that Android Studio Preview depends on the current language settings of macOS.
> Perhaps macOS language settings are used [in this section](https://github.com/DroidKaigi/conference-app-2023/blob/main/core/designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2023/designsystem/strings/Lang.kt#L6) in Preview.
> If I change the language setting of macOS to English, the Preview will be in English.

Make sense... I could reproduce that by changing the system language too 🤦‍♂️

> This is fine when built into the Android JVM environment, but in the Android Studio JVM environment, the code needs to be rewritten to depend on the externally given value (the Locale value in Preview).

I tried to overwrite the locale forcibly in preview, `Write access not allowed during rendering (user.language)   at java.util.Locale.setDefault  at java.util.Locale.setDefault` was displayed 😢

> The problem is that how this can be accomplished still needs to be investigated. 😕

That's true... And I think you would like to take other exciting tasks, so please don't hesitate to unassign yourself from this issue if wanted 🙏

**Comment by mikanIchinose** [comment] 2023-08-16 03:51
How about using `androidx.compose.ui.text.intl.Locale.current.language` instead of `java.util.Locale.getDefault().language`?

**Comment by tkhs0604** [comment] 2023-08-16 04:20
@mikanIchinose 
Wow! I misunderstood that it can be used within the composable functions 😮
It seems to work well by using `androidx.compose.ui.text.intl.Locale.current.language`! Could you make a pull request for that?
![image](https://github.com/DroidKaigi/conference-app-2023/assets/43767445/de172c88-99a3-4998-9a47-c30c967146f4)

**Closed** 2023-08-16 10:53 UTC
Labels: help wanted, welcome contribute
