### ISSUE TITLE
a crash occurs on the contributor screen when clicks 'UP' button

### ISSUE THREAD

**Issue by fornewid** [DroidKaigi/conference-app-2023#529] opened 2023-08-15 13:01 UTC
**Describe the bug**

**To Reproduce**
1. Go to the contributor screen
2. Click UP button
3. Crash occurs

**Expected behavior**

1️⃣ Navigate to previous screen. (without crash)
or 
2️⃣ Hide UP button.

**Screenshots**

<kbd>
<img width="300" src="https://github.com/DroidKaigi/conference-app-2023/assets/3405740/ff36afe4-8e4e-45e0-a97c-11c4ee3c7320" />
</kbd>

**Comment by naotama2002** [comment] 2023-08-15 14:20
According to [Figma design](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI), the Contributor should not be placed in Bottom Navigation should it transition from the Abort screen?

Or should it transition from both the Abort screen and Bottom Navigation?

**Comment by takahirom** [comment] 2023-08-15 14:25
You are correct. The reason we are currently displaying the contributor in the bottom navigation is that it's vital to collaborate with the contributor during this early phase of development. We plan to remove it from the bottom navigation in the future.

**Comment by takahirom** [comment] 2023-08-15 14:26
So maybe this is intended behavior. Let me close this 🙇

**Closed by takahirom** 2023-08-15 14:26 UTC
Labels: welcome contribute
