### ISSUE TITLE
Modify the color of the card on the timetable detail screen.

### ISSUE THREAD

**Issue by WonJoongLee** [DroidKaigi/conference-app-2023#514] opened 2023-08-15 02:22 UTC
**Idea Description**
- In the timetable detail screen, there is a card, which card background color is different with figma. It has to be changed because the background color is different.
- The color of the card background is `Surface Container Low`.

**Reference images and links**
- You can find that `Surface at elevation +1 becomes Surface Container Low` from the Material Design Blog's article. ([link](https://material.io/blog/tone-based-surface-color-m3))
- [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=54902-39762&mode=design&t=aFRgTz4zGl3mBbFQ-4)
- The code is located at `TimetableItemDetailSummaryCard.kt`.

**Comment by takahirom** [comment] 2023-08-15 02:26
Thanks for making this issue!

**Comment by Hachimori** [comment] 2023-08-15 11:04
🙋

**Comment by takahirom** [comment] 2023-08-15 14:13
Thanks!

**Comment by Hachimori** [comment] 2023-08-15 16:04
The issue should be fixed after merging #528.

The problem is that the color theme for `Surface`  in [Color.kt](https://github.com/DroidKaigi/conference-app-2023/blob/main/core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched2023/designsystem/theme/Color.kt#L25) is different from what [Figma](https://www.figma.com/file/MbElhCEnjqnuodmvwabh9K/DroidKaigi-2023-App-UI?type=design&node-id=56041-40062&mode=dev) specifies.

In #528, @tfandkusu fixes color theme for `Surface`. Also, Surface's elevation is already +1 because from [TimetableItemDetailSummaryCard.kt](https://github.com/DroidKaigi/conference-app-2023/blob/e5caf2593ef7b2dd86d74427e887dc24e69353a3/feature/sessions/src/main/java/io/github/droidkaigi/confsched2023/sessions/component/TimetableItemDetailSummaryCard.kt#L39-L42)'s implementation, it does:

```
colors = CardDefaults.cardColors(
    containerColor = MaterialTheme.colorScheme.surfaceColorAtElevation(
        1.dp,
    ),
),
```

which makes the Surface's elevation +1.

After applying #528's changes, the screen will look as follows:

## Light mode
| Before  | After |
| ------------- | ------------- |
| ![before_light](https://github.com/DroidKaigi/conference-app-2023/assets/3529042/4036c788-3199-4e1f-a521-405043f34c11) | ![after_light](https://github.com/DroidKaigi/conference-app-2023/assets/3529042/9d1d0618-fe8a-4d88-9cdf-c2708427c1ed) |


## Dark mode
| Before  | After |
| ------------- | ------------- |
| ![before_dark](https://github.com/DroidKaigi/conference-app-2023/assets/3529042/b0061360-db18-4bcb-b366-662488bcf450) | ![after_dark](https://github.com/DroidKaigi/conference-app-2023/assets/3529042/c38db19c-d7da-41b0-bc7a-4ffadfa1e82c) |

**Comment by takahirom** [comment] 2023-08-15 16:37
Thanks for your report! Let's wait for 528 merge🙏

**Comment by Hachimori** [comment] 2023-08-17 09:21
#528 was merged.
I guess that this issue can be closed now 😀

**Comment by takahirom** [comment] 2023-08-17 16:24
Thanks for telling me!

**Closed by takahirom** 2023-08-17 16:24 UTC
Labels: welcome contribute
